### ISSUE TITLE
Cmdlet is Missing for Bulk Group Assign

### ISSUE THREAD

**Issue by FiberNut** [paulleblond/OktaBulkGroupAssign#1]
Have been looking for some solution to bulk assign Users to Groups in Okta, and from a CSV-- this fits the bill-- but when the PS files are downloaded and in place, running the command "OktaBulkGroupAssign" reveals there is no such cmdlet provided in the package. Running a Get-Command -Module Okta | Sort-Object -Property Noun | Format-Table -GroupBy Noun = many many commands-- but "oktaBulkGroupAssign" is missing, so running the script throws that "is not recognized as the name of a cmdlet, function, script file, or operable program" message.
Was it removed for some reason?
:(

**Comment by paulleblond** [comment]
This is a command line executable, not a powershell cmdlet.  You may be able to run an exe from Powershell, but that is outside the scope of this project.
